services:
  - type: web
    name: vidsnap-ai
    env: docker
    plan: free
    region: oregon
    branch: main
    envVars:
      - key: PORT
        value: 10000
      - key: ELEVENLABS_API_KEY
        sync: false # User will input their key securely in the Render GUI dashboard
